// packages/core/src/index.ts — the public surface.
export * from "./types.ts";
export { detectBot, BOT_RULES, BOT_TABLE_VERSION, type BotVerdict } from "./bots.ts";
export {
  AgentKeys,
  agentTrust,
  verifyAgent,
  jwkThumbprint,
  signatureBase,
  parseSignatureInput,
  parseSignature,
  parseSignatureAgent,
  DIRECTORY_PATH,
  SKEW_MS,
  type AgentTrust,
  type AgentReason,
  type AgentVerdict,
  type Jwk,
} from "./agent.ts";
export {
  classifyReferrer,
  parseUtm,
  hostOf,
  aiSourceOf,
  AI_HOSTS,
  SEARCH_HOSTS,
  SOCIAL_HOSTS,
  EMAIL_HOSTS,
  REFERRER_TABLE_VERSION,
  type ReferrerVerdict,
} from "./referrers.ts";
export { parseUa, type UaVerdict } from "./ua.ts";
export { countryFromHeaders, COUNTRY_HEADERS, geoFromHeaders, roundCoord, EMPTY_GEO, GEO_PROVIDERS, type Geo, type GeoProvider } from "./geo.ts";
export { COUNTRIES, countryName, countryPoint, type Country } from "./countries.ts";
export { normalizeIp, ipv6Prefix64 } from "./ip.ts";
export {
  policyFor,
  POLICIES,
  STRICT_TRADEOFFS,
  stripReferrer,
  blockedByDoNotTrack,
  type PrivacyMode,
  type PrivacyPolicy,
} from "./privacy.ts";
export { visitorId, identityId, dayKey, SESSION_WINDOW_MS } from "./visitor.ts";
export { validateEvent, LIMITS, type ValidationResult } from "./validate.ts";
export { Ingestor, splitUrl, type IngestOptions, type IngestResult } from "./ingest.ts";
export { type Store, SCHEMA_VERSION } from "./store/store.ts";
export { SqliteStore } from "./store/sqlite.ts";
export {
  buildBundle,
  windowOf,
  previousWindow,
  evidenceOf,
  bucketFor,
  bucketForGranularity,
  GRANULARITIES,
  WindowError,
  type Granularity,
  LIVE_WINDOW_MS,
  MAX_SERIES_POINTS,
  type MetricBundle,
  type Evidence,
  type TimeWindow,
  type SeriesPoint,
} from "./metrics/bundle.ts";
export {
  METRICS,
  metricsFor,
  metricById,
  HUMAN,
  HUMAN_STRICT,
  AGENT_SESSION,
  SUSPECT_SCORE,
  type MetricDef,
} from "./metrics/queries.ts";
export {
  headerSignals,
  describeSignals,
  serializeSignals,
  parseSignals,
  score,
  suspected,
  SUSPECT_AT,
  SIGNAL_TABLE_VERSION,
  type Signal,
} from "./signals.ts";
export {
  FILTER_FIELDS,
  FILTER_LABELS,
  FILTER_OPS,
  OP_LABELS,
  FilterError,
  applyFilters,
  describeFilters,
  filterValues,
  isFilterField,
  isPropField,
  fieldLabel,
  isFilterOp,
  parseFilters,
  resolvePatternFilters,
  serializeFilters,
  windowCount,
  type Filter,
  type FilterField,
  type FilterOp,
  type PropField,
} from "./metrics/filters.ts";
export {
  listSessions,
  sessionTimeline,
  listUsers,
  userProfile,
  eventDetail,
  errorOccurrences,
  computeJourneys,
  computeGoal,
  validateGoal,
  pathPatternRegex,
  filterSuggestions,
  GoalError,
  MAX_JOURNEY_STEPS,
  MAX_JOURNEYS,
  type Query,
  type Scope,
  type Select,
  type SessionRow,
  type SessionEvent,
  type UserRow,
  type UserProfile,
  type EventDetail,
  type JourneyResult,
  type Goal,
  type GoalResult,
} from "./metrics/explore.ts";
export {
  buildGeoReport,
  GEO_METRICS,
  GEO_SESSION_LIMIT,
  GEO_POINT_LIMIT,
  type GeoReport,
} from "./metrics/geo.ts";
export {
  computePerformance,
  PerformanceError,
  VITAL_KEYS,
  PERCENTILES,
  PERF_DIMENSIONS,
  type PerformanceResult,
  type VitalKey,
} from "./metrics/performance.ts";
export {
  computeFunnel,
  buildFunnelSql,
  validateSteps,
  defaultFunnel,
  FunnelError,
  MAX_FUNNEL_STEPS,
  type FunnelStep,
  type FunnelResult,
  type FunnelStepResult,
} from "./metrics/funnel.ts";
export {
  computeRetention,
  MAX_COHORTS,
  MAX_OFFSET,
  type RetentionResult,
  type RetentionUnavailable,
  type RetentionCohort,
} from "./metrics/retention.ts";
export { guardProse, extractNumbers, checkCausality, type GuardResult } from "./insight/guard.ts";
export { composeDigest, renderText, fmt, type Digest, type DigestLine } from "./insight/compose.ts";
export {
  slackBlocks,
  sendSlack,
  emailSubject,
  emailHtml,
  HttpEmailSender,
  NullEmailSender,
  type EmailSender,
  type DeliveryTarget,
  type DeliveryResult,
} from "./deliver/channels.ts";
export {
  tick,
  migrateDelivery,
  addSubscription,
  listSubscriptions,
  removeSubscription,
  alreadySent,
  recordSent,
  worthSending,
  periodStart,
  windowForPeriod,
  deliveryKey,
  DELIVERY_DDL,
  type Subscription,
  type Cadence,
  type TickOutcome,
  type TickDeps,
} from "./deliver/scheduler.ts";
export {
  phraseDigest,
  buildPrompt,
  OllamaClient,
  OpenAiCompatClient,
  type LlmClient,
  type PhraseOutcome,
} from "./insight/llm.ts";
export {
  REPLAY_DDL,
  REPLAY_EVENT,
  REPLAY_LIMITS,
  REPLAY_BOUNDS,
  DEFAULT_REPLAY_SETTINGS,
  ReplayError,
  migrateReplay,
  getReplaySettings,
  setReplaySettings,
  replayConfig,
  replayOptedOut,
  sampledIn,
  decodeChunk,
  sanitizeChunk,
  maskValue,
  ingestReplayChunk,
  purgeExpiredReplays,
  listReplays,
  loadReplay,
  deleteReplay,
  deleteAllReplays,
  displayName,
  type ReplaySettings,
  type ReplayRequest,
  type ReplayVerdict,
  type ReplayHooks,
  type ReplayIngestResult,
  type ReplayChunkInput,
  type ReplayListFilters,
  type ReplayRow,
  type ReplayMarker,
  type ReplayPlayback,
} from "./replay.ts";
export { REPLAY_PLAYER_JS } from "./replay-player.ts";
export { replayPublicRoute, replaySiteApi, type PublicReplayOptions, type SiteReplayOptions } from "./replay-http.ts";
